development:
  adapter: postgresql
  encoding: unicode
  database: socketchat_development
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

test:
  adapter: postgresql
  encoding: unicode
  database: socketchat_test
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

production:
  adapter: postgresql
  encoding: unicode
  database: socketchat_production
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>